/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as KuaaaGalleryIndexImport } from './routes/kuaaa-gallery/index'
import { Route as KuaaaGalleryBhnbImport } from './routes/kuaaa-gallery/bhnb'
import { Route as KuaaaGalleryItemIdImport } from './routes/kuaaa-gallery/$itemId'

// Create/Update Routes

const KuaaaGalleryIndexRoute = KuaaaGalleryIndexImport.update({
  id: '/kuaaa-gallery/',
  path: '/kuaaa-gallery/',
  getParentRoute: () => rootRoute,
} as any)

const KuaaaGalleryBhnbRoute = KuaaaGalleryBhnbImport.update({
  id: '/kuaaa-gallery/bhnb',
  path: '/kuaaa-gallery/bhnb',
  getParentRoute: () => rootRoute,
} as any)

const KuaaaGalleryItemIdRoute = KuaaaGalleryItemIdImport.update({
  id: '/kuaaa-gallery/$itemId',
  path: '/kuaaa-gallery/$itemId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kuaaa-gallery/$itemId': {
      id: '/kuaaa-gallery/$itemId'
      path: '/kuaaa-gallery/$itemId'
      fullPath: '/kuaaa-gallery/$itemId'
      preLoaderRoute: typeof KuaaaGalleryItemIdImport
      parentRoute: typeof rootRoute
    }
    '/kuaaa-gallery/bhnb': {
      id: '/kuaaa-gallery/bhnb'
      path: '/kuaaa-gallery/bhnb'
      fullPath: '/kuaaa-gallery/bhnb'
      preLoaderRoute: typeof KuaaaGalleryBhnbImport
      parentRoute: typeof rootRoute
    }
    '/kuaaa-gallery/': {
      id: '/kuaaa-gallery/'
      path: '/kuaaa-gallery'
      fullPath: '/kuaaa-gallery'
      preLoaderRoute: typeof KuaaaGalleryIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/kuaaa-gallery/$itemId': typeof KuaaaGalleryItemIdRoute
  '/kuaaa-gallery/bhnb': typeof KuaaaGalleryBhnbRoute
  '/kuaaa-gallery': typeof KuaaaGalleryIndexRoute
}

export interface FileRoutesByTo {
  '/kuaaa-gallery/$itemId': typeof KuaaaGalleryItemIdRoute
  '/kuaaa-gallery/bhnb': typeof KuaaaGalleryBhnbRoute
  '/kuaaa-gallery': typeof KuaaaGalleryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/kuaaa-gallery/$itemId': typeof KuaaaGalleryItemIdRoute
  '/kuaaa-gallery/bhnb': typeof KuaaaGalleryBhnbRoute
  '/kuaaa-gallery/': typeof KuaaaGalleryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/kuaaa-gallery/$itemId' | '/kuaaa-gallery/bhnb' | '/kuaaa-gallery'
  fileRoutesByTo: FileRoutesByTo
  to: '/kuaaa-gallery/$itemId' | '/kuaaa-gallery/bhnb' | '/kuaaa-gallery'
  id:
    | '__root__'
    | '/kuaaa-gallery/$itemId'
    | '/kuaaa-gallery/bhnb'
    | '/kuaaa-gallery/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  KuaaaGalleryItemIdRoute: typeof KuaaaGalleryItemIdRoute
  KuaaaGalleryBhnbRoute: typeof KuaaaGalleryBhnbRoute
  KuaaaGalleryIndexRoute: typeof KuaaaGalleryIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  KuaaaGalleryItemIdRoute: KuaaaGalleryItemIdRoute,
  KuaaaGalleryBhnbRoute: KuaaaGalleryBhnbRoute,
  KuaaaGalleryIndexRoute: KuaaaGalleryIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/kuaaa-gallery/$itemId",
        "/kuaaa-gallery/bhnb",
        "/kuaaa-gallery/"
      ]
    },
    "/kuaaa-gallery/$itemId": {
      "filePath": "kuaaa-gallery/$itemId.tsx"
    },
    "/kuaaa-gallery/bhnb": {
      "filePath": "kuaaa-gallery/bhnb.tsx"
    },
    "/kuaaa-gallery/": {
      "filePath": "kuaaa-gallery/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
